#################### default parameters ################################
# favicon
favicon = "images/favicon.png" # TODO - Look into changing favicon 
# logo
logo = "images/logo.png"  # TODO - Look into changing logo
# use `x` with logo_width, example: "100x"
logo_width = "150px"
# logo text will only show when logo is missing.
logo_text = "TH"
# OpenGraph / Twitter Card metadata
description = "A place to share my thoughts"
author = "Tony Hammack"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# main sections
mainSections = ["blog"]
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# copyright text
copyright = 'This work is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).'
notice = "_All opinions expressed are my own._"
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# author
[author_block]
title= "Tony Hammack"
image= "images/avatar.png"  # TODO -> Change to use a picture of me.
content= """
I talk to computers all day and drink (too much) coffee.

I mostly write about personal growth or nerdy math/tech related things.
"""

# Preloader
[preloader]
enable = true 
preloader = "" # use jpg, png, svg or gif format.

# cookies
[cookies]
enable = true 
expire_days = 1
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
icon = "fab fa-linkedin-in"
link = "https://www.linkedin.com/in/hammack-tony"

[[social]]
icon = "fab fa-github"
link = "https://www.github.com/hammacktony"

[[social]]
icon = "fas fa-envelope"
link = "mailto:hammack.tony@gmail.com"
